services:
  stats-server:
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1

  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    networks:
      - ewm-net
    ports:
      - "9092:9092" # for client connections
      - "9101:9101" # JMX
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

    kafka-init-topics:
      image: confluentinc/confluent-local:7.4.3
      container_name: kafka-init-topics
      depends_on:
        - kafka
      command: "bash -c \
                  'kafka-topics --create --topic stats.user-actions.v1 \
                               --partitions 1 --replication-factor 1 --if-not-exists \
                               --bootstrap-server kafka:29092 && \
                  kafka-topics --create --topic stats.events-similarity.v1 \
                               --partitions 1 --replication-factor 1 --if-not-exists \
                               --bootstrap-server kafka:29092'"
      init: true

#services:
#  stats-server:
#    build: ./stat/stat-server
#    image: ewm-stats-server
#    container_name: ewm-stats-server
#    ports:
#      - "9090:9090"
#    depends_on:
#      - stats-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
#      - SPRING_DATASOURCE_USERNAME=stats-db
#      - SPRING_DATASOURCE_PASSWORD=secret
#
#  stats-db:
#    image: postgres:16.1
#    container_name: stats-db
#    ports:
#      - "15432:5432"
#    volumes:
#      - statData:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_DB=stats-db
#      - POSTGRES_USER=stats-db
#      - POSTGRES_PASSWORD=secret
#    healthcheck:
#      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
#      timeout: 5s
#      interval: 5s
#      retries: 10
#
#  ewm-service:
#    build: ./main-service
#    image: ewm-server
#    container_name: ewm-server
#    ports:
#      - "8080:8080"
#    depends_on:
#      - ewm-db
#    environment:
#      - STAT_SERVER_URI=http://stats-server:9090
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
#      - SPRING_DATASOURCE_USERNAME=ewm-db
#      - SPRING_DATASOURCE_PASSWORD=secret
#
#  ewm-db:
#    image: postgres:16.1
#    container_name: ewm-db
#    ports:
#      - "25432:5432"
#    volumes:
#      - mainData:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_DB=ewm-db
#      - POSTGRES_USER=ewm-db
#      - POSTGRES_PASSWORD=secret
#    healthcheck:
#      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
#      timeout: 5s
#      interval: 5s
#      retries: 10
#
#
#volumes:
#  statData:
#    driver: local
#  mainData:
#    driver: local