server:
  port: 0

statsServiceId: stats-server

spring:
  application:
    name: comment-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: comment_schema
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/ewm_comment
    username: main
    password: main