server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/users/*/comments/**, /admin/comments/**

        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**, /users/*/events/*/requests/**

        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/events/**, /users/*/events/**, /admin/events/**, /compilations/**, /admin/compilations/**, /admin/categories/**, /categories/**

        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**