server:
  port: 1234
#stats-server:
#  uri: "${STAT_SERVER_URI}"
#stats-server:
#  uri: "${STAT_SERVER_URI:http://localhost:9090}"
#stats-server:
#  uri: "${STAT_SERVER_URI:http://stats-server:9090}"
