server:
  port: 0

statsServiceId: stats-server

spring:
  application:
    name: event-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: event_schema
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:25432/ewm-db
    driver-class-name: "org.postgresql.Driver"
    username: "ewm-db"
    password: "secret"