server:
  port: 0

#stats-server:
#  uri: "${STAT_SERVER_URI}"

statsServiceId: stat-server

spring:
  application:
    name: main-service
  config:
    import: "optional:configserver:"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hibernate:
          format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:25432/ewm-db
    driver-class-name: "org.postgresql.Driver"
    username: "ewm-db"
    password: "secret"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10