server:
  port: 0
spring:
  application:
    name: stat-server
  config:
    import: "optional:configserver:"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hibernate:
          format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:15432/stats-db
    driver-class-name: "org.postgresql.Driver"
    username: "stats-db"
    password: "secret"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10

#spring:
#  config:
#    activate:
#      on-profile: "test"
#  datasource:
#    url: jdbc:h2:mem:stats-db
#    driver-class-name: "org.h2.Driver"
#    username: "stats-db"
#    password: "secret"
#    url: "jdbc:h2:file:./db/svc_db.mv.db"
#    driverClassName: "org.h2.Driver"
#    username: "svc"
#    password: "qwe123"
#  h2:
#    console:
#      enabled: true